name: b2qatesting

on:
  push:
    branches:
      - developer
  schedule:
    - cron: '00 0 * * *' 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
         java-version: '15'
         distribution: 'adopt'
    - name: Build with Maven
      run: mvn -f pomdevauto.xml clean install
    - name: Test Reporter
      uses: dorny/test-reporter@v1.4.3
      with:
        name: Run Tests
        path: "**/surefire-reports/TEST-*.xml"
        reporter: java-junit
    - name: Test Reporter
      uses: cinotify/github-action@main
      with:
        to: 'hariprasad@bamboobox.ai'
        subject: 'building main'
        body: 'This is a notification from GitHub actions.'
      
