name: Docker Image C1
on:
   push:
     branches: [ main ]
   pull_request:
jobs:
   build:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2
     - name: Build the Docker image
       run: docker build . -t myimage1:1.0
     - uses: docker/login-action@v2
     - name: Login to docker hub
       with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
     
     
