name: Docker Image C1
on:
   push:
     branches: [ main ]
   pull_request:
jobs:
   build:
     runs-on: ubuntu-latest
     steps:
     - name: Build the Docker image
       uses: actions/checkout@v2
     - run: docker build . -t myimage1:1.0
       
     - name: Login to docker hub
       uses: docker/login-action@v1
       with:
         username: ${{ secrets.ranik123k }}
         password: ${{ secrets.dckr_pat_6W67w47khS4-cW9-p1jWFVM4t2o }}
         logout: true
      
     - name: push to docker hub
       uses: docker/build-push-action@v2
       with:
         push: true
         tags: <removed>:latest
         
     - name: Image digest
       run: echo ${{ steps.docker_build.outputs.digest }}
       
     - name: Save state
       run: echo "{name}={value}" >> $GITHUB_STATE

     - name: Set output
       run: echo "{name}={value}" >> $GITHUB_OUTPUT
         
         
       
     
     
     
